### ISSUE TITLE
"File" content type causes the export to fail

### ISSUE THREAD

**Issue by frapell** [Shriyanshagro/plone.importexport#1]
When running the export on a site with a "File" object fails with the following error:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.importexport.browser.view, line 323, in export
  Module plone.importexport.browser.view, line 236, in serialize
  Module plone.importexport.browser.view, line 236, in serialize
  Module plone.importexport.browser.view, line 218, in serialize
  Module plone.restapi.serializer.dxcontent, line 77, in __call__
  Module plone.restapi.serializer.dxfields, line 24, in __call__
  Module plone.restapi.serializer.converters, line 34, in json_compatible
  Module zope.component.hookable, line 33, in __call__
  Module zope.component.hooks, line 104, in adapter_hook
  Module plone.restapi.serializer.converters, line 60, in list_converter
  Module plone.restapi.serializer.converters, line 34, in json_compatible
  Module zope.component.hookable, line 33, in __call__
  Module zope.component.hooks, line 104, in adapter_hook
  Module plone.restapi.serializer.relationfield, line 17, in relationvalue_converter
  Module plone.restapi.serializer.summary, line 31, in __call__
  Module plone.app.contentlisting.realobject, line 70, in review_state
  Module Products.CMFCore.WorkflowTool, line 263, in getInfoFor
WorkflowException: No workflow provides '${name}' information.
```

Steps to reproduce:

1) Create a site from scratch using the buildout provided in the product
2) Add a "File" content
3) Try to run the export

**Comment by Shriyanshagro** [comment]
Please share the file-type and if possible the file as well. I have already tested it with various file-types with a positive result, except for videos. Support for Videos will be soon added.

**Comment by frapell** [comment]
@Shriyanshagro Sorry, I was inaccurate with the steps to reproduce. You need to add a file as a related item in order to see the exception, so on a site from scratch do:

1) Add a file object (Using any type of file)
2) Add a page, and from the "Categorization" tab, go to the "Related items" and choose the file added in step 1
3) When trying to export the site, you get the exception.

This is caused by the fact that Files do not have a workflow

**Comment by Shriyanshagro** [comment]
issue followed on #5
