### ISSUE TITLE
Handle UID in richtext links and images

### ISSUE THREAD

**Issue by frapell** [Shriyanshagro/plone.importexport#3]
An internal link in a richtext field, is exported as follows:

```
<a data-val="5f4a9f6417944ebfa1ebba98f045840c" href="http://localhost:8080/Plone/page-1" data-linktype="internal">Link</a>
```

This fails, when importing the data back to a site with an id different than "Plone". Furthermore, the UID would be wrong, since it is generated on creation.

A possible idea for solution could be:

 * Save the content UID in the CSV when exporting
 * Then, when importing, keep a dictionary map with "old UID" -> "new UID"
 * When importing the richtext data, check the UID from this map and rewrite the data-val with the new UID
 * Fix the href to reflect the new location. (I'm not sure, but I think you can just throw away the href attribute and the transformation in Plone would re-create it when rendering)

**Comment by Shriyanshagro** [comment]
Need to resolve the case when importing content into a fresh site, but the object that is referred in UID is yet to be created in further steps.

Current Solution:
import twice to completely replicate the site, as in the first time some UID may not be mapped.

Error log:
currently, it has been logged as Deserialization error in log file, for the first fresh import

**Comment by frapell** [comment]
This is not an "enhancement", and instead, it is a "bug", since this is basic functionality, the internal links for the site after being imported should continue to work, as they used to previously.

I don't think it is ok to log an error, that will pollute the log with information that should be ignored. A proper way of fixing this would be to first create all the elements in the site, and then fill the richtext fields as needed doing the proper UID replacements, and so, there would not be any errors in the logs.

Also, notice that you can close tickets directly from the commit message:

https://help.github.com/articles/closing-issues-via-commit-messages/

That helps to keep track in the future how each ticket was fixed, so you don't need to track the whole commit log to try to find it.

Also, if you just want to do a commit but do not close the ticket, because you are still working on it, you can just reference the ticket number https://help.github.com/articles/autolinked-references-and-urls/

Just for reference, this ticket was closed with this commit https://github.com/Shriyanshagro/plone.importexport/commit/59c85acc7254eb826a9309b172518db8c13d489c
