### ISSUE TITLE
Internal links are not correct

### ISSUE THREAD

**Issue by frapell** [Shriyanshagro/plone.importexport#6]
@Shriyanshagro This is related to #3 

While the UID part is indeed correct, the href still points to the old site.

Steps to reproduce:

1) Create a Plone site with id "Plone"
2) Create 2 pages, "Page 1" and "Page 2"
3) From "Page 2" create an internal link to "Page 1"
4) Export the content
5) Create a second site called "Plone2"
6) Import the content exported on step 4

At this point, while the UID in data-val properly point to the new UID for "Page 1", the href points to "../../Plone/page-1"

The correct value for "href" should be href="resolveuid/UID_FOR_PAGE1"

(check the source code of the richtext saved in page-2 from Plone and compare with Plone2)

**Comment by Shriyanshagro** [comment]
Right. So now this issue could only be resolved by examing every anchor tag individually using a python HTML parser probably BeautifulSoup4?
Any better solution to this?

**Comment by frapell** [comment]
@Shriyanshagro Yes, you are right, this needs the HTML to be fixed, and for doing so you can use lxml or BeautifulSoup.

lxml would be better because it is already being used in Plone so you don't need to include an additional dependency, but is a bit more difficult to use than BS.
